version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-engine-backend
    container_name: devskiller-blog-engine-backend
    command: /usr/src/app/node_modules/.bin/nodemon server.js
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: .env.docker
    environment:
      - NODE_ENV=development
    networks:
      - app-network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: blog-engine-frontend
    container_name: devskiller-blog-engine-frontend
    command: npm start
    environment:
      - REACT_HTTP_PROXY=http://backend:5000
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - app-network
  mongo:
    image: mongo
    container_name: devskiller-blog-engine-mongodb
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local
